version: "3.9"

services:

  backend:
    build: ./chatflow_backend
    ports:
      - "8000:8000"
    volumes:
      - ./chatflow_backend:/app

  frontend:
    build: ./chatflow_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./chatflow_frontend:/app
    depends_on:
      - backend