# Generated by Django 6.0.4 on 2026-05-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
