# Generated by Django 6.0.4 on 2026-09-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0002_alter_room_slug_alter_topic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaupload',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
