# Generated by Django 6.0.4 on 2026-06-19 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0002_user_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Direct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('craeted_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='massage.massage')),
                ('user_Direct', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
