# Generated by Django 6.0.4 on 2026-06-19 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massage', '0003_alter_user_account_username_direct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direct',
            name='chat',
        ),
        migrations.AddField(
            model_name='massage',
            name='direct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='massage.direct'),
        ),
    ]
